apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - common
  - environment/easytrade-ingress.yml

patches:
  - path: environment/kubernetes-labels-patch.yml
    target:
        kind: Deployment

images:
- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/accountservice
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/aggregator-service
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/broker-service
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/calculationservice
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/contentcreator
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/credit-card-order-service
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/db
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/engine
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/feature-flag-service
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/frontend
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/frontendreverseproxy
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/loadgen
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/loginservice
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/manager
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/offerservice
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/pricing-service
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/rabbitmq
  newTag: "4d5adb3"

- name: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/third-party-service
  newTag: "4d5adb3"
