manifestVersion: 1.0
projects:
  - name: workshop
    path: ./workshop
environmentGroups:
  - name: workshop-environment-group
    environments:
      - name: workshop-environment
        url:
          type: environment
          value: DT_TENANT_3GEN
        auth:
          token:
            type: environment
            name: MONACO_TOKEN
          oAuth:
            clientId:
              type: environment
              name: CLIENT_ID
            clientSecret:
              type: environment
              name: CLIENT_SECRET
            tokenEndpoint:
              type: environment
              value: SSO_ENDPOINT
