# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendreverseproxy
  labels:
    app: frontendreverseproxy
spec:
  selector:
    matchLabels:
      app: frontendreverseproxy
  template:
    metadata:
      labels:
        app: frontendreverseproxy
    spec:
      containers:
        - name: frontendreverseproxy
          image: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade/frontendreverseproxy:4d5adb3
          ports:
            - containerPort: 80
          env: []
          resources:
            requests:
              cpu: 50m
              memory: 75Mi
            limits:
              memory: 75Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontendreverseproxy-easytrade
spec:
  type: LoadBalancer
  selector:
    app: frontendreverseproxy
  ports:
    - name: http
      port: 80
      targetPort: 80
